name: GitHub Classroom Workflow

on: [push]

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: education/autograding@v1
      - uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
            files: build/test-results/**/*.xml